version: "3.8"

services:
  paano-front:
    build:
      ./paano-front
    ports:
      - "8080:3000"
    restart: always
  paano-back:
    build:
      ./paano-back
    ports:
      - "8082:8082"
    restart: always
  rvp:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always


